import 'package:food_app/model/product.dart';
import 'package:food_app/model/shop.dart';

List<Shop> shops = [
  Shop(
      1,
      "Angkringan Resto",
      "assets/images/shop_1.png",
      2,
      [
        Product(
          1,
          "Ice Cream Yummiii !!",
          5.99,
          2,
          true,
          false,
          ["Fruits", "Ice Cream"],
          description,
          "assets/images/ice cream.png",
          "assets/images/ice-cream-preview.png",
          "Angkringan Resto",
          true,
          4.99,
        ),
        Product(
          2,
          "Pink Ice",
          6.99,
          2,
          false,
          true,
          ["Fruits", "Ice Cream"],
          description,
          "assets/images/pink_ice.png",
          "assets/images/pink_ice.png",
          "Angkringan Resto",
          false,
          0,
        ),
        Product(
          3,
          "Blue Ice",
          8.99,
          2,
          false,
          false,
          ["Fruits", "Ice Cream"],
          description,
          "assets/images/blue_ice.png",
          "assets/images/blue_ice.png",
          "Angkringan Resto",
          true,
          5.99,
        ),
      ],
      ["", "", ""],
      ["Ice Cream", "Snack", "Coffee", "Cake"],
      "Jawi, Pasuruan"),
  Shop(
    2,
    "Blembem Coffee Shop",
    "assets/images/shop_2.png",
    3,
    [
      Product(
        4,
        "Sponge Cake",
        12.99,
        2,
        true,
        false,
        ["Sweet Cake"],
        description,
        "assets/images/sponge cake.png",
        "assets/images/sponge cake.png",
        "Blembem Coffee Shop",
        false,
        0,
      ),
    ],
    [],
    ["Sweet Cake"],
    "Nort Surabaya",
  ),
  Shop(
      3,
      "Jawicenter Resto",
      "assets/images/shop_3.png",
      2,
      [
        Product(
          4,
          "Sweet Donut",
          12.99,
          2,
          true,
          false,
          ["Sweet Cake", "Donut"],
          description,
          "assets/images/sponge cake.png",
          "assets/images/sponge cake.png",
          "Jawicenter Resto",
          false,
          0,
        ),
      ],
      [],
      ["Sweet Cake", "Donut"],
      "Pasuruan"),
  Shop(4, "Blembem Coffee Shop", "assets/images/shop_4.png", 3, [], [], [],
      "Nort Surabaya"),
];

String description =
    "Nibh faucibus pellentesque ac viverra maecenas ultricies in nisl, faucibus pellentesque ac viverra ecenas ultricies in nisl";
